name: bluebuild

on:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
        # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds

jobs:
  bluebuild:
    name: Build Custom Image

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails

      matrix:
        include:
          - recipe: workstation
            arch: x86_64
            variant: fedora-release-kinoite-41-38.noarch
            version: 41
            maximize_build_space: true

          - recipe: workstation-nvidia
            arch: x86_64
            variant: fedora-release-kinoite-41-38.noarch
            version: 41
            maximize_build_space: true

          - recipe: laptop
            arch: x86_64
            variant: fedora-release-kinoite-41-38.noarch
            version: 41
            maximize_build_space: true

          - recipe: k8s-node
            arch: x86_64
            variant: fedora-release-coreos-41-38.noarch
            version: 41
            maximize_build_space: false

          - recipe: k8s-node-hci-zfs-nvidia
            arch: x86_64
            variant: fedora-release-coreos-41-38.noarch
            version: 41
            maximize_build_space: false

          - recipe: server
            arch: x86_64
            variant: fedora-release-coreos-41-38.noarch
            version: 41
            maximize_build_space: false

          - recipe: bazzite
            arch: x86_64
            variant: fedora-release-coreos-41-38.noarch
            version: 41
            maximize_build_space: true

    steps:
      # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.8.1
        with:
          recipe: ${{ matrix.recipe }}.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: ${{ matrix.maximize_build_space }}
