name: weekly-update

on:
  schedule:
    - cron: "00 06 * * TUE,FRI"

  workflow_dispatch:
    inputs:
      skip_base:
        type: boolean
        description: Skip base image builds
        required: false
        default: false

jobs:
  base-bluebuild:
    name: Build Bases

    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.skip_base != 'true' }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - recipe: _kinoite
          - recipe: _kinoite-nvidia
          - recipe: _bazzite-deck
          - recipe: _server-zfs
          - recipe: _server

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.11.1
        with:
          recipe: ${{ matrix.recipe }}.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          maximize_build_space: true
          rechunk: false

  image-bluebuild:
    name: Build Images

    runs-on: ubuntu-latest

    needs:
      - base-bluebuild

    strategy:
      fail-fast: false

      matrix:
        include:
          - recipe: bazzite-deck
          - recipe: bazzite-deck-touch
          - recipe: k8s-node-zfs
          - recipe: k8s-node
          - recipe: server
          - recipe: workstation-kinoite
          - recipe: workstation-kinoite-nvidia

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.11.1
        with:
          recipe: ${{ matrix.recipe }}.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          maximize_build_space: true
          rechunk: false

  image-bluebuild-skipped:
    name: Build Images

    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.skip_base == 'true' }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - recipe: bazzite-deck
          - recipe: bazzite-deck-touch
          - recipe: k8s-node-zfs
          - recipe: k8s-node
          - recipe: server
          - recipe: workstation-kinoite
          - recipe: workstation-kinoite-nvidia

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.11.1
        with:
          recipe: ${{ matrix.recipe }}.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          maximize_build_space: true
          rechunk: false
